# Generated by Django 3.0.5 on 2021-08-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('high', models.DecimalField(decimal_places=6, max_digits=16)),
                ('p_close', models.DecimalField(decimal_places=6, max_digits=16)),
                ('p_low', models.DecimalField(decimal_places=6, max_digits=16)),
                ('p_open', models.DecimalField(decimal_places=6, max_digits=16)),
            ],
        ),
    ]
