# Generated by Django 3.0.5 on 2021-08-25 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 25, 17, 25, 20, 107737, tzinfo=utc)),
        ),
    ]
