# Generated by Django 3.0.5 on 2021-08-22 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equity',
            old_name='high',
            new_name='p_high',
        ),
    ]
