# Generated by Django 3.0.5 on 2021-08-22 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0002_auto_20210822_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='md_date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
