# Generated by Django 3.0.5 on 2021-08-24 15:57

import apps.dividends.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equities', '0003_equity_md_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('dividends', djongo.models.fields.ArrayField(model_container=apps.dividends.models.DividendList, model_form_class=apps.dividends.models.DividendListForm)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equities.Equity')),
            ],
        ),
    ]
