# Generated by Django 3.0.5 on 2021-08-25 17:25

import apps.dividends.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('date_time', models.DateTimeField(default=datetime.datetime(2021, 8, 25, 17, 25, 10, 449690, tzinfo=utc))),
                ('dividends', djongo.models.fields.ArrayField(model_container=apps.dividends.models.DividendList, model_form_class=apps.dividends.models.DividendListForm)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equities.Equity')),
            ],
        ),
    ]
